name: omics-reg
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake==7.32.4
  - r-base>=4.3,<4.4
  - r-bestNormalize
  - r-boruta
  - r-data.table
  - r-embed
  - r-ggbeeswarm
  - r-ggrepel
  - r-gridExtra
  - r-matrixStats
  - r-mikropml
  - r-shapviz
  - r-tidymodels
  - r-tidyverse
  - r-xgboost

